trailingComma: "es5"
semi: false
singleQuote: false
jsxSingleQuote: false
useTabs: true
tabWidth: 2
printWidth: 160
endOfLine: lf
overrides:
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
